name: bro
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  animated_text_kit: ^4.2.1
  font_awesome_flutter: ^9.0.0
  flutter_icons: ^1.1.0
  url_launcher: ^6.0.3
  share: ^2.0.1
  flutter_svg: ^0.22.0
  
  


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  
  
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - images/
    - assets/images/weightloss.svg
    - assets/workout_gif/chest/barbell bench press.gif
    - assets/workout_gif/chest/BarbellDeclineBenchPress.gif
    - assets/workout_gif/chest/BarbellInclineBenchPressChest.gif
    - assets/workout_gif/chest/BarbellCloseGripBenchPressUpperArms.gif
    - assets/workout_gif/chest/DumbbellBenchPressChest.gif
    - assets/workout_gif/chest/DumbbellDeclineBenchPressChess.gif
    - assets/workout_gif/chest/ChestDipChest.gif
    - assets/workout_gif/chest/AssistedChestDipkneelingChest.gif
    - assets/workout_gif/chest/SmithBenchPressChest360.gif
    - assets/workout_gif/chest/SmithInclineBenchPressChest.gif
    - assets/workout_gif/chest/SmithDeclineBenchPressChest360.gif
    - assets/workout_gif/chest/LeverChestPress.gif
    - assets/workout_gif/chest/LeverInclineChestPressChest.gif
    - assets/workout_gif/chest/DumbbellLyingHammerPressChest.gif
    - assets/workout_gif/chest/DumbbellDeclineFlyChest.gif
    - assets/workout_gif/chest/DumbbellInclineFlyChest.gif
    - assets/workout_gif/chest/DumbbellInclineHammerPressChest.gif
    - assets/workout_gif/chest/LeverSeatedFlyChest.gif
    - assets/workout_gif/chest/CableMiddleFlyChest.gif
    - assets/workout_gif/chest/CableInclineFlyChest.gif
    - assets/workout_gif/chest/CableLowFlyChest.gif
    - assets/workout_gif/chest/CableStandingUpStraightCrossoversChest.gif
    #Back
    - assets/workout_gif/back/BackExtensions.gif
    - assets/workout_gif/back/BarbellBentOverRowBack _ underhand grip.gif
    - assets/workout_gif/back/BarbellInclineRowBack.gif
    - assets/workout_gif/back/CablePalmRotationalRowBack.gif
    - assets/workout_gif/back/Chin-Up_Back.gif
    - assets/workout_gif/back/Dumbbell-Bent-Over-Row.gif
    - assets/workout_gif/back/DumbbellRow.gif  
    - assets/workout_gif/back/LatPullDown.gif
    - assets/workout_gif/back/LeverBentoverRowplateloadedBack.gif
    - assets/workout_gif/back/WeightedPullUp.gif
    - assets/workout_gif/back/Cable-Straight-Back-Seated-Row_Back.gif
    #shoulder
    - assets/workout_gif/shoulder/
    #core
    - assets/workout_gif/core/
    #leg
    - assets/workout_gif/leg/
    #bicep
    - assets/workout_gif/biceps/
    #tricep
    - assets/workout_gif/tricep/
    #compound
    - assets/workout_gif/compound/
     

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Cornerstone
      fonts:
        - asset: fonts/Cornerstone.ttf
    - family: SixCaps
      fonts:
        - asset: fonts/SixCaps.ttf
    - family: Oswald
      fonts:
        - asset: fonts/Oswald-SemiBold.ttf
          weight: 500
        - asset: fonts/Oswald-Regular.ttf
          weight: 400
        - asset: fonts/Oswald-Medium.ttf
          weight: 300
        - asset: fonts/Oswald-Light.ttf
          weight: 200
        - asset: fonts/Oswald-ExtraLight.ttf
          weight: 100
    # - family: Schyler
    #   fonts:
    #     - asset: fonts/Schyler-Regular.ttf
    #     - asset: fonts/Schyler-Italic.ttf
    #       style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
